#include "pixelboost/db/types/common.h"
#include "pixelboost/db/register.h"

PB_DB_BEGIN_STRUCT(Vector2)
    PB_DB_FIELD_FLOAT(X)
    PB_DB_FIELD_FLOAT(Y)
PB_DB_END_STRUCT

PB_DB_BEGIN_STRUCT(Vector3)
    PB_DB_FIELD_FLOAT(X)
    PB_DB_FIELD_FLOAT(Y)
    PB_DB_FIELD_FLOAT(Z)
PB_DB_END_STRUCT

PB_DB_BEGIN_STRUCT(Color)
    PB_DB_FIELD_FLOAT(R)
    PB_DB_FIELD_FLOAT(G)
    PB_DB_FIELD_FLOAT(B)
    PB_DB_FIELD_FLOAT(A)
PB_DB_END_STRUCT
